Editor/color picker improve and fix mapping ui/ux
Kirakira-Games/BanGround-Unity pull request #142
Opened 2021-08-14 13:53 UTC by AECBanana

add login can use enter key login~

2021-08-15 00:37 UTC, KCFindstr requested changes

2021-08-15 00:37 UTC, KCFindstr commented on Assets/Codes/Mapping/Components/ColorPicker.cs
> +        DisableListener();
使用SetTextWithoutNotify，不要反复disable和enable listener

2021-08-15 00:37 UTC, KCFindstr commented on Assets/Codes/Mapping/Controllers/MetaDataController.cs
> +            SceneLoader.LoadSceneAsync("Mapping");
为什么要重新载入mapping场景？

2021-08-15 00:37 UTC, KCFindstr commented on Assets/Codes/Mapping/Core/ChartCore.cs
> +            }
这个实现可扩展性太差了 换成mod面板（开始时可以只放auto进去 剩下的mod慢慢加）

2021-08-15 00:37 UTC, KCFindstr commented on Assets/Codes/Mapping/Core/ChartCore.cs
> +             SceneLoader.Back(null);
这是在干什么 按退出按钮后支持取消？为什么不增加一个选项 而是强制要求退出时保存谱面？
以及这个if为什么不写成
```csharp
if (await messageBox.ShowMessage("Editor.Title.Exit".L(), "Editor.Prompt.Exit".L()))
{
    Save();
    SceneLoader.Back(null);
}
```

2021-08-15 00:37 UTC, KCFindstr commented on Assets/Codes/Select/SelectManager.cs
> +        if (authing)
在任何地方修改过authing的值吗？这个变量存在的意义是什么？

2021-08-15 00:37 UTC, KCFindstr commented on Assets/Codes/Select/SelectManager.cs
> +    public bool authing = false;
private

2021-08-15 00:40 UTC, KCFindstr commented on Assets/Codes/Mapping/Controllers/MetaDataController.cs
> +            SceneLoader.LoadSceneAsync("Mapping");
如果是为了更新部分meta，不要使用这个实现，而是找到需要更新的组件进行更新。直接重载场景会丢失当前保存的大量状态信息。

2021-08-15 04:45 UTC, AECBanana commented on Assets/Codes/Mapping/Core/ChartCore.cs
> +            }
这个椰叶写吧 实在不会

2021-08-15 04:46 UTC, AECBanana commented on Assets/Codes/Select/SelectManager.cs
> +        if (authing)
好像是可以让编辑器没登陆的情况下也被锁在外面。。编辑器直接用select场景打开的话是不会登录的 要title才可以

2021-08-16 01:21 UTC, KCFindstr commented on Assets/Codes/Select/SelectManager.cs
> +        if (authing)
那为什么authing的值没有被修改过？这不是一个unused variable？

2021-08-18 06:22 UTC, MCsentic commented
这个pr描述和标题怎么不一致

2021-08-25 07:09 UTC, GEEKiDoS commented on Assets/Scenes/Select.unity
> +  m_Size: 0.11743186
煞笔unity能不能别乱动size

2021-08-25 07:09 UTC, GEEKiDoS commented on Assets/Scenes/Select.unity
> +  m_XRTrackingOrigin: {fileID: 0}
草

2021-08-25 07:11 UTC, GEEKiDoS commented on Assets/Codes/Select/SelectManager.cs
> +    private SettingPanel settingAndMod;
那能不能把名字顺便改了

2021-08-25 07:11 UTC, GEEKiDoS commented on Assets/Codes/Select/OffsetGuide.cs
> +    SettingPanel settingAndMod;
+

2021-08-25 07:11 UTC, GEEKiDoS commented on Assets/Codes/Injector/SelectInstaller.cs
> +        Container.Bind<SettingPanel>().FromInstance(settingAndMod);
+

2021-08-25 07:11 UTC, GEEKiDoS commented on Assets/Codes/Injector/SelectInstaller.cs
> +    public SettingPanel settingAndMod;
+

2021-08-25 07:13 UTC, GEEKiDoS commented on Assets/Codes/Mapping/Components/EditorPlayHandler.cs
> +            float seekTime = fromStart ? 0 : audioManager.gameBGM.GetPlaybackTime() / 1000f;
有个问题 在从中间放的时候能不能把入场动画关了 @LingFeng-bbben

2021-08-25 07:20 UTC, KCFindstr commented on Assets/Codes/Select/SelectManager.cs
> +    private SettingPanel settingAndMod;
vs太蠢了 不自动帮我改 但是我已经上床了 @MCsentic 来邦邦把这些conversation都解决了

2021-08-28 00:15 UTC, KCFindstr approved these changes

2021-08-28 00:18 UTC, KCFindstr requested changes
添加英语i18n文本

2021-08-28 00:36 UTC, KCFindstr approved these changes

2021-08-28 00:40 UTC, Frenqy approved these changes

2021-08-28 00:45 UTC, merged