Fix #141
Kirakira-Games/BanGround-Unity pull request #145
Opened 2021-08-15 15:20 UTC by MCsentic

### 变动
1. Input System 1.1.0-preview.3 => 1.1.0-pre.5
2. 关闭RunInBackground
3. 其他package变动是因为unity版本更新之后自动升级的

### 效果
![image](https://user-images.githubusercontent.com/28777951/129483419-f285148c-173a-48b6-8e4c-3cc364c2b85b.png)

2021-08-15 22:22 UTC, KCFindstr requested changes

2021-08-15 22:22 UTC, KCFindstr commented on ProjectSettings/ProjectSettings.asset
> +  m_ShowUnitySplashLogo: 1
?

2021-08-16 01:35 UTC, MCsentic commented on ProjectSettings/ProjectSettings.asset
> +  m_ShowUnitySplashLogo: 1
提交pr的人只要unity没付费都这样，理论上不应该要求修改
@KCFindstr 需要在release分支的bot上修改

2021-08-16 03:42 UTC, KCFindstr approved these changes

2021-08-16 03:42 UTC, merged