E/l view select count
Kirakira-Games/BanGround-Unity pull request #150
Opened 2021-08-28 03:27 UTC by AECBanana

2021-08-28 04:48 UTC, KCFindstr requested changes

2021-08-28 04:48 UTC, KCFindstr commented on Assets/Codes/Result/DeplayDetail.cs
> +        const int max =  224;
为什么要hard code，这是miss区间吗？

2021-08-28 04:48 UTC, KCFindstr commented on Assets/Codes/Result/DeplayDetail.cs
> +        float maxHeight = 0;
height全是整数吗？

2021-08-28 04:48 UTC, KCFindstr commented on Assets/Codes/Result/DeplayDetail.cs
> +            }
这是个桶排？有点怪，我想重写

2021-08-28 04:48 UTC, KCFindstr commented on Assets/Codes/Select/DifficultySelect.cs
> +            int counter = 0;
这是个匀速的数字变化动画？建议做成单独component，继承Text

2021-08-28 04:48 UTC, KCFindstr commented on Assets/Codes/Select/DifficultySelect.cs
> +
是不是缓动好一点 TransitionLib里有相关实现

2021-08-28 04:48 UTC, KCFindstr commented on Assets/Codes/Select/DifficultySelect.cs
> +                levelText.text = start.ToString();
这段代码也太怪了
1. 为什么不使用for？
2. 为什么要使用固定增量而不用lerp？这样会积累误差。

2021-08-28 04:48 UTC, KCFindstr commented on Assets/Codes/Select/DifficultySelect.cs
> +
为什么要先变成0再变成target value

2021-08-28 04:48 UTC, KCFindstr commented on Assets/Codes/Select/DifficultySelect.cs
> +        changeLevelCancelSource = new CancellationTokenSource();
这里内存漏了，没有dispose token source

2021-08-28 04:51 UTC, KCFindstr commented on Assets/Codes/Select/DifficultySelect.cs
> +                levelText.text = start.ToString();
上面s<12的时候v=0，这段动画根本不会动，建议换成lerp

2021-08-28 04:53 UTC, KCFindstr commented on Assets/Codes/Select/DifficultySelect.cs
> +            int counter = 0;
做成个通用组件吧，支持指定transition，只支持数值输入，不一定需要继承Text，可以
```csharp
[RequireComponent(typeof(Text))]
```

2021-08-28 06:10 UTC, AECBanana commented on Assets/Codes/Select/DifficultySelect.cs
> +
因为是甲方要求（我

2021-08-28 23:57 UTC, GEEKiDoS commented on Assets/Codes/Result/DeplayDetail.cs
> +        const int max =  224;
我数的妹弓那几个条下面的数字

2021-08-28 23:57 UTC, GEEKiDoS commented on Assets/Codes/Result/DeplayDetail.cs
> +        float maxHeight = 0;
啥意思

2021-08-28 23:57 UTC, GEEKiDoS commented on Assets/Codes/Result/DeplayDetail.cs
> +            }
写

2021-08-28 23:58 UTC, GEEKiDoS commented on Assets/Codes/Result/DeplayDetail.cs
> +            }
我瞎jb写的

2021-08-28 23:59 UTC, GEEKiDoS commented on Assets/Codes/Result/DeplayDetail.cs
> +            }
其实上面已经排过了 这里只是找出这些元素对应的条

2021-08-29 05:23 UTC, GEEKiDoS commented on Assets/Codes/AnimatedIntegerText.cs
> +                    if (target == 0)
如果next是0不就爆爆爆爆了

2021-08-29 05:54 UTC, KCFindstr approved these changes
LGTM

2021-08-29 06:04 UTC, merged